name = "OpenSSL"
uuid = "4d8831e6-92b7-49fb-bdf8-b643e874388c"
authors = ["Greg Lapinski <grzegorz.lapinski@live.com>", "Jacob Quinn <quinn.jacobd@gmail.com>"]
version = "1.4.2"

[deps]
BitFlags = "d1d4a3ce-64b1-5f1a-9ba4-7e7e69966f35"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
MozillaCACerts_jll = "14a3606d-f60d-562e-9121-12d972cd8159"
OpenSSL_jll = "458c3c95-2e84-50aa-8efc-19380b2a3a95"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[compat]
BitFlags = "0.1"
MozillaCACerts_jll = ">= 2020"
OpenSSL_jll = "1.1, 3.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
